//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTelefonica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AgendaTelefonica.Models;
    
    public partial class DBContatosEntities1 : DbContext
    {
        public DBContatosEntities1()
            : base("name=DBContatosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Models.Contatos> Contatos { get; set; }
        public virtual DbSet<Models.Usuarios> Usuarios { get; set; }
    }
}
